# Generated by Django 4.2 on 2023-05-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficher', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellai', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_projet', models.ImageField(upload_to='')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('acheve', models.BooleanField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ficher_CV', models.FileField(upload_to='')),
                ('ficher_photo', models.ImageField(upload_to='')),
                ('lien_linkedln', models.URLField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='projet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.projet'),
        ),
    ]
