# Generated by Django 4.2 on 2023-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_projet_acheve'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='acheve',
            field=models.BooleanField(default=False),
        ),
    ]
