# Generated by Django 4.2 on 2023-05-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_projet_acheve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='details',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='image_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('DG', 'Design Graphique'), ('PA', 'Production Audiovisuelle'), ('3D', 'Conception 3D')], default='3D', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='projet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.projet'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='ficher_CV',
            field=models.FileField(max_length=255, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='ficher_photo',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='acheve',
            field=models.CharField(choices=[('o', 'Oui'), ('n', 'Non')], default='o', max_length=255),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='personnel',
            name='Equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.equipe'),
        ),
    ]
