# Generated by Django 4.2 on 2023-05-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_personnel_equipe_remove_projet_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='Equipe',
            new_name='equipe',
        ),
    ]
