# Generated by Django 4.2 on 2023-05-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_projet_img_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotreModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
            ],
        ),
    ]
