# Generated by Django 4.2 on 2023-05-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_votremodele'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VotreModele',
        ),
    ]
