# Generated by Django 4.2 on 2023-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_equipe_projet_remove_personnel_equipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='per',
            new_name='personnels',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='equipe',
            new_name='Equipe',
        ),
        migrations.AlterField(
            model_name='detail',
            name='ficher',
            field=models.FileField(max_length=255, upload_to='uploads/'),
        ),
    ]
