# Generated by Django 4.2 on 2023-05-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_per_equipe_personnels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='ficher_CV',
            field=models.FileField(max_length=255, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='ficher_photo',
            field=models.ImageField(max_length=255, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
