# Generated by Django 4.2 on 2023-05-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_equipe_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='Equipe',
        ),
        migrations.AddField(
            model_name='equipe',
            name='Projet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.projet'),
        ),
    ]
