# Generated by Django 4.2 on 2023-05-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_projet_equipe_equipe_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='Projet',
        ),
        migrations.AddField(
            model_name='personnel',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default=' ', max_length=255),
        ),
    ]
