# Generated by Django 4.2 on 2023-05-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_personnel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='personnels',
            new_name='personnel',
        ),
        migrations.AddField(
            model_name='equipe',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.projet'),
            preserve_default=False,
        ),
    ]
