# Generated by Django 4.2 on 2023-05-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_personnel_equipe_personnels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='equipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.equipe'),
        ),
    ]
