# Generated by Django 4.2 on 2023-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_equipe_personnels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='personnels',
            field=models.ManyToManyField(to='user.personnel'),
        ),
    ]
