# Generated by Django 4.1.7 on 2023-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_equipe_personnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
