# Generated by Django 4.1.7 on 2023-05-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_projetutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='en_cours',
        ),
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='projet',
        ),
        migrations.AddField(
            model_name='projetutilisateur',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projetutilisateur',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projetutilisateur',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projetutilisateur',
            name='img_projet',
            field=models.ImageField(max_length=255, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='projetutilisateur',
            name='libellai',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
