# Generated by Django 4.1.7 on 2023-05-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_projetutilisateur_en_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='img_projet',
        ),
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='libellai',
        ),
        migrations.AddField(
            model_name='projetutilisateur',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.projet'),
        ),
    ]
