# Generated by Django 4.1.7 on 2023-05-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_projetutilisateur_projet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetutilisateur',
            name='projet',
        ),
        migrations.AddField(
            model_name='projetutilisateur',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.projet'),
        ),
    ]
